#!/usr/bin/python
#my first Class
class Person:
    def setName(self, name):
        self.name = name
    def getName(self):
        return self.name
    def greet(self):
        print("Hello , world! I'm %s."%self.name)
foo = Person()
foo.setName("flyCoder")
foo.greet()
